### ISSUE TITLE
Dictionary changed size during iteration

### ISSUE THREAD

**Issue by Muzry** [softwarefactory-project/DLRN#33] opened 2017-07-28 04:02 UTC
when I use DLRN to process rpms with concurrent, occur following problem:
Traceback (most recent call last):
File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
self.run()
File "/usr/lib64/python2.7/threading.py", line 764, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/lib64/python2.7/multiprocessing/pool.py", line 342, in _handle_tasks
put(task)
RuntimeError: dictionary changed size during iteration

How to deal with this problem?

**Comment by javierpena** [comment] 2017-08-02 16:58
I have tried to reproduce this issue locally, setting workers=3 in projects.ini, but it didn't fail for me. Could you share some details about your environment:

- Comnand-line used to build the packages
- Contents of projects.ini
- Which version of DLRN you are using (commit hash if downloaded from source)

Thanks!

**Comment by Muzry** [comment] 2017-08-08 12:07
Thank you for replying this issue.  This problem occurred occasionally, our environment flavor is 16 CPU 32G RAM.

This is my environment configs:

- #### Command-line
   - dlrn --config projects.ini --info-repo xxxxx --head-only --local

- #### Contents of projects.ini

``` cfg
[DEFAULT]
...
tags=mitaka
pkginfo_driver=dlrn.drivers.rdoinfo.RdoInfoDriver
rsyncdest=
rsyncport=22
workers=10
gerrit_topic=rdo-FTBFS
...
```

- #### version of DLRN
   - commit is 7a24a338ab24fce72b45059cce66b35f1e70b0d5

**Comment by javierpena** [comment] 2017-09-13 16:50
I think I have finally found the reason. https://bugs.python.org/issue23051 matches this issue, so the fix should come via a python update.

I'll investigate into this, a fix for CentOS could require some time.

**Comment by javierpena** [comment] 2019-10-07 13:20
The Python bug is fixed, so closing.

**Closed by javierpena** 2019-10-07 13:20 UTC
