### ISSUE TITLE
delorean can exit without building anything and without feedback

### ISSUE THREAD

**Issue by dmsimard** [softwarefactory-project/DLRN#11] opened 2015-09-21 15:27 UTC
See:

```
$ delorean --config-file projects.ini --local --package-name python-openstackclient; echo $?
INFO:delorean:Getting git://github.com/openstack-packages/python-openstackclient to ./data/python-openstackclient_distro
INFO:delorean:Getting git://git.openstack.org/openstack/python-openstackclient to ./data/python-openstackclient
0
```

(that's it)
- There are no rpmbuild.log files generated.
- Nothing in audit.log

Need to find some time to troubleshoot further.

**Comment by dtantsur** [comment] 2015-09-22 07:16
This, for example, happened to me when I provided wrong command line flags

**Comment by dmsimard** [comment] 2016-01-12 16:07
So @trown let me know this is related to the commits.sqlite file.

It goes like this:
- Run delorean once on a package
(data is generated in delorean/data and commits.sqlite file is updated in delorean/commits.sqlite)
- Delete delorean/data
- Run delorean again on the same package
- Returns without nothing as described in OP

Moving or deleting the commits.sqlite resolves this issue so it looks like we could handle that better.

**Comment by javierpena** [comment] 2016-01-12 16:19
@dmsimard in the example you provided, Delorean is working as designed. It stored the latest commit number for the uptream and dist-git repos in the database, and it did not re-create the package because there was no change in any of them.

It you need to run delorean on the same data more than one, use the --dev flag.

**Comment by dmsimard** [comment] 2016-01-12 16:22
@javierpena it's okay if it's meant to be like that but it should at least tell you something and not just exit  without telling you anything. It's not very user friendly :)

**Comment by snecklifter** [comment] 2017-07-09 17:19
Yeah, I agree with @dmsimard it would be nice to output something, I am just onboarding and this was confusing, I didn't know what had actually happened.

**Comment by javierpena** [comment] 2017-07-11 07:38
Ok, it would make sense to make DLRN report that no commits can be built for the common reasons (no new commit or non-existing package). I've added it to https://softwarefactory-project.io/storyboard/#!/story/206

**Comment by javierpena** [comment] 2019-10-07 13:26
This was fixed in https://softwarefactory-project.io/r/9277

**Closed by javierpena** 2019-10-07 13:26 UTC
